"""
database.py  --  In-Memory Restaurant & Menu Database
=====================================================
Loads the JSON data generated by data_generator.py and provides
fast query methods with filtering.

AI Concept: Feature Store / Data Access Layer
---------------------------------------------
In production ML systems, a "feature store" separates raw data from
the ML models that consume it.  This module acts as a lightweight
feature store:

  * Loads data once at startup (O(1) per request).
  * Provides filter methods that the LLM pipeline calls with
    structured parameters extracted from user queries.
  * Returns rich dicts that the ranking engine scores.

Design choice: We keep everything in memory (50 restaurants,
300+ items) because latency matters for a chatbot. In production,
this would be backed by PostgreSQL / Elasticsearch.
"""

import json
import os
import math
from typing import List, Optional

DATA_DIR = "data"


def _haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """
    Great-circle distance (km) between two (lat, lon) points.

    AI Concept: Geospatial Filtering
    ---------------------------------
    Distance is one of the strongest features in food delivery ranking.
    Users overwhelmingly prefer nearby restaurants (delivery time ∝ distance).
    The Haversine formula works well for distances < 100 km.
    """
    R = 6371
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (math.sin(dlat / 2) ** 2 +
         math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) *
         math.sin(dlon / 2) ** 2)
    return R * 2 * math.asin(math.sqrt(a))


class FoodDatabase:
    """
    In-memory restaurant + menu database with filtering.

    AI Concept: Candidate Generation
    ---------------------------------
    Before the ranking model scores restaurants, we need a fast
    "candidate generation" step that narrows 50 restaurants down to
    10-15 that match the user's hard constraints (price, diet, cuisine,
    distance).  This is the classic two-stage recommendation pattern:

      Stage 1: candidate generation  (this module -- cheap filters)
      Stage 2: ranking               (ranker.py -- ML scoring)
    """

    def __init__(self, data_dir: str = DATA_DIR):
        rest_path = os.path.join(data_dir, "restaurants.json")
        menu_path = os.path.join(data_dir, "menu_items.json")

        with open(rest_path, "r", encoding="utf-8") as f:
            self.restaurants: List[dict] = json.load(f)
        with open(menu_path, "r", encoding="utf-8") as f:
            self.menu_items: List[dict] = json.load(f)

        # Index: restaurant_id -> restaurant dict
        self.rest_by_id = {r["id"]: r for r in self.restaurants}

        # Index: restaurant_id -> [menu_item, ...]
        self.menu_by_rest: dict[int, list] = {}
        for item in self.menu_items:
            rid = item["restaurant_id"]
            self.menu_by_rest.setdefault(rid, []).append(item)

        # Collect all known locations for fuzzy matching
        self.known_locations = list({r["location"] for r in self.restaurants})

    def search(
        self,
        price_limit: Optional[float] = None,
        cuisine: Optional[str] = None,
        diet_type: Optional[str] = None,
        tags: Optional[List[str]] = None,
        meal_time: Optional[str] = None,
        location: Optional[str] = None,
        user_lat: Optional[float] = None,
        user_lon: Optional[float] = None,
        max_distance_km: Optional[float] = None,
    ) -> List[dict]:
        """
        Filter restaurants + menu items by the user's constraints.

        AI Concept: Structured Query from NL Params
        --------------------------------------------
        The LLM extracts structured parameters from natural language
        (e.g., "spicy chicken under ₹300 near Kukatpally" -> 
         {diet_type: non-veg, tags: [spicy], cuisine: North Indian,
          price_limit: 300, location: Kukatpally}).

        This method converts those params into database filters.
        Each filter is applied independently (AND logic), narrowing
        the candidate set progressively.

        Returns a list of dicts:
          {restaurant: {...}, item: {...}, distance_km: float}
        """
        results = []

        for rest in self.restaurants:
            if not rest.get("is_open", True):
                continue

            # --- Location / distance filter ---
            distance_km = None
            if user_lat is not None and user_lon is not None:
                distance_km = round(_haversine_km(
                    user_lat, user_lon, rest["lat"], rest["lon"]
                ), 2)
                if max_distance_km and distance_km > max_distance_km:
                    continue

            # Location name filter (fuzzy match on area name)
            if location:
                loc_lower = location.lower()
                rest_loc_lower = rest["location"].lower()
                if loc_lower not in rest_loc_lower and rest_loc_lower not in loc_lower:
                    continue

            # --- Menu-level filters ---
            items = self.menu_by_rest.get(rest["id"], [])
            for item in items:
                # Price filter
                if price_limit and item["price"] > price_limit:
                    continue

                # Cuisine filter
                if cuisine:
                    if cuisine.lower() not in item["cuisine"].lower():
                        continue

                # Diet type filter
                if diet_type:
                    dt = diet_type.lower()
                    item_diet = item["diet_type"].lower()
                    # "healthy" is a tag, not a diet type
                    if dt in ("healthy", "spicy", "light", "comfort",
                              "protein-rich", "low-calorie", "keto",
                              "gluten-free", "high-fibre"):
                        if dt not in [t.lower() for t in item.get("tags", [])]:
                            continue
                    elif dt == "vegetarian" or dt == "veg":
                        if item_diet not in ("veg", "vegan"):
                            continue
                    elif dt == "non-veg" or dt == "non-vegetarian":
                        if item_diet != "non-veg":
                            continue
                    elif dt == "vegan":
                        if item_diet != "vegan":
                            continue
                    else:
                        if dt not in item_diet:
                            continue

                # Tag filter
                if tags:
                    item_tags = [t.lower() for t in item.get("tags", [])]
                    if not any(t.lower() in item_tags for t in tags):
                        continue

                # Meal-time filter
                if meal_time:
                    if item["meal_time"] != "all-day" and meal_time.lower() != item["meal_time"].lower():
                        continue

                results.append({
                    "restaurant": rest,
                    "item": item,
                    "distance_km": distance_km,
                })

        return results

    def get_location_coords(self, location_name: str) -> Optional[dict]:
        """
        Get approximate coordinates for a known location name.

        AI Concept: Geocoding Fallback
        -------------------------------
        When the user says "near Kukatpally" but doesn't provide GPS,
        we geocode using our known-locations lookup table. In production,
        this would call a geocoding API (Google Maps, Nominatim).
        """
        for loc in KNOWN_COORDS:
            if location_name.lower() in loc["name"].lower() or loc["name"].lower() in location_name.lower():
                return {"lat": loc["lat"], "lon": loc["lon"]}
        return None

    def get_items_with_offers(
        self,
        user_lat: Optional[float] = None,
        user_lon: Optional[float] = None,
    ) -> List[dict]:
        """
        Return all menu items / restaurants that have an active offer.

        Items are returned if either the restaurant or the item itself
        has an offer.  The offer label is attached at item level for
        easy downstream rendering.

        AI Concept: Intent-specific retrieval
        --------------------------------------
        When the user asks for "offers", we skip the normal filter
        pipeline and instead query a different index / predicate.
        This is analogous to how production systems maintain separate
        "deals" or "promotions" indices.
        """
        results = []
        for rest in self.restaurants:
            if not rest.get("is_open", True):
                continue

            distance_km = None
            if user_lat is not None and user_lon is not None:
                distance_km = round(_haversine_km(
                    user_lat, user_lon, rest["lat"], rest["lon"]
                ), 2)

            rest_offer = rest.get("offer")
            items = self.menu_by_rest.get(rest["id"], [])

            for item in items:
                item_offer = item.get("offer")
                # Keep this item if it or its restaurant has an offer
                if not item_offer and not rest_offer:
                    continue

                # Prefer item-level offer; fall back to restaurant offer
                effective_offer = item_offer or rest_offer

                results.append({
                    "restaurant": rest,
                    "item": item,
                    "distance_km": distance_km,
                    "offer": effective_offer,
                })

        return results


# Pre-built location coordinates for geocoding
KNOWN_COORDS = [
    {"name": "Kukatpally",     "lat": 17.4947, "lon": 78.3996},
    {"name": "Madhapur",       "lat": 17.4486, "lon": 78.3908},
    {"name": "Gachibowli",     "lat": 17.4401, "lon": 78.3489},
    {"name": "Hitech City",    "lat": 17.4435, "lon": 78.3772},
    {"name": "Banjara Hills",  "lat": 17.4156, "lon": 78.4347},
    {"name": "Jubilee Hills",  "lat": 17.4325, "lon": 78.4073},
    {"name": "Kondapur",       "lat": 17.4600, "lon": 78.3548},
    {"name": "Ameerpet",       "lat": 17.4375, "lon": 78.4483},
    {"name": "Begumpet",       "lat": 17.4440, "lon": 78.4674},
    {"name": "Secunderabad",   "lat": 17.4399, "lon": 78.4983},
    {"name": "Dilsukhnagar",   "lat": 17.3688, "lon": 78.5247},
    {"name": "LB Nagar",       "lat": 17.3457, "lon": 78.5522},
    {"name": "Miyapur",        "lat": 17.4969, "lon": 78.3548},
    {"name": "Tolichowki",     "lat": 17.3950, "lon": 78.4139},
    {"name": "Mehdipatnam",    "lat": 17.3950, "lon": 78.4400},
    {"name": "KPHB",           "lat": 17.4835, "lon": 78.3880},
    {"name": "Moosapet",       "lat": 17.4700, "lon": 78.4250},
    {"name": "SR Nagar",       "lat": 17.4450, "lon": 78.4500},
]
